# Generated by Django 4.0.6 on 2022-07-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('short_description', models.CharField(max_length=500)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
                ('image3', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_title', models.CharField(max_length=50)),
                ('cateogry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_shop.category')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product_shop.gender')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_chart', models.CharField(blank=True, choices=[('S', 'small'), ('L', 'large'), ('M', 'medium'), ('XL', 'xtra large'), ('XXL', 'double xtra large')], default='S', max_length=5)),
                ('cloth_size', models.IntegerField(blank=True)),
                ('foot_size', models.IntegerField(blank=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product_shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1*'), (2, '2*'), (3, '3*'), (4, '4*'), (5, '5*')], null=True)),
                ('reviews', models.TextField()),
                ('images', models.FileField(blank=True, upload_to='static/user_review_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product_shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_shop.subcategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_shop.gender'),
        ),
    ]
